@startuml
autonumber

actor Usuario as user
participant "Menu" as menu
participant "OperacionesImpl" as operacionesImpl
participant "Televisor" as televisor

user -> menu: anadirTelevision()
user <-- menu: Solicitar datos del televisor
user -> menu: Ingresar datos (precio, marca, nombre, tipo de pantalla, pulgadas)

menu -> operacionesImpl: Validar marca
user <-- operacionesImpl: throw new ExcepcionAnadirTelevisor ("la marca no es válida")
operacionesImpl --> menu: Marca válida
menu -> operacionesImpl: agregarTelevisor()

operacionesImpl -> televisor: Televisor televisor = new Televisor()
operacionesImpl <-- televisor: televisor

operacionesImpl -> operacionesImpl: listaArticulos.add(televisor)
operacionesImpl --> menu: Televisor registrado

menu -> user: Confirmar registro exitoso

@enduml